# Database
db=postgres
db-url-host=${KC_DB_HOST:postgres}
db-url-database=${KC_DB_NAME:keycloak}
db-username=${KC_DB_USER:keycloak}
db-password=${KC_DB_PASSWORD:keycloak}

# HTTP
http-enabled=true
http-port=8080
hostname-strict=false

# Health
health-enabled=true
