using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using System.Text.Json;

namespace WeatherApi.Controllers;

[ApiController]
[Route("auth")]
public class AuthController(HttpClient _httpClient) : ControllerBase
{
    [HttpPost("login-by-code")]
    [AllowAnonymous]
    public async Task<IActionResult> LoginByCode([FromBody] LoginRequestBody body)
    {
        const string _baseUrl = "http://keycloak:8080";
        const string _clientId = "weather-api";
        const string _realm = "dev";
        string clientSecret = Environment.GetEnvironmentVariable("CLIENT_SECRET") ??
                throw new("Add the CLIENT_SECRET generated by your local keycloak server to the .env file at the project root!");
        var content = new FormUrlEncodedContent(new Dictionary<string, string>
        {
            { "grant_type", "authorization_code" },
            { "code", body.Code },
            { "client_id", _clientId },
            { "client_secret", clientSecret },
            { "redirect_uri", body.RedirectUri }
        });

        var response = await _httpClient.PostAsync($"{_baseUrl}/realms/{_realm}/protocol/openid-connect/token", content);
        response.EnsureSuccessStatusCode();
        var json = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(json);
        var accessToken = doc.RootElement.GetProperty("access_token").GetString();
        var username = GetUsernameClaim(accessToken);

        List<Claim> claims = [];
        if (!string.IsNullOrEmpty(username.Value))
        {
            claims.Add(new Claim(nameof(username), username.Value));
        }

        return Ok(new { accessToken = CreateToken(claims) });
    }

    public record LoginRequestBody(string Code, string RedirectUri);

    Claim GetUsernameClaim(string? token)
    {
        var handler = new JwtSecurityTokenHandler();
        var jwt = handler.ReadJwtToken(token);
        return jwt.Claims.FirstOrDefault(c => c.Type == "username" || c.Type == "preferred_username")
            ?? throw new Exception("Username claim not found");
    }

    string CreateToken(List<Claim> claims)
    {
        const int _defaultExpiresInMinutes = 1;
        const string _key = "7F9aP2LkQxM4WJtE8RZsD0HnYcB5U3Vv";
        const string _issuer = "http://localhost";
        const string _audience = "weather-api";

        var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_key));
        var credentials = new SigningCredentials(key, SecurityAlgorithms.HmacSha256);
        var token = new JwtSecurityToken(
            issuer: _issuer,
            audience: _audience,
            claims: claims,
            notBefore: DateTime.UtcNow,
            expires: DateTime.UtcNow.AddMinutes(_defaultExpiresInMinutes),
            signingCredentials: credentials
        );

        return new JwtSecurityTokenHandler().WriteToken(token);
    }
}
