events {}
http {
  server {
    listen 80;

    root /usr/share/nginx/;

    location / {
      try_files $uri /index.html;
    }

    location /weather {
      proxy_pass http://weather-service:8000/;
      proxy_set_header Host $host;
    }
  }
}