# Database
db=postgres
db-url-host=postgres
db-url-database=keycloak
db-username=keycloak
db-password=${KC_DB_PASSWORD:keycloak}

# HTTP
http-enabled=true
http-port=8080
hostname-strict=false

# Health
health-enabled=true
