using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text.Json;

namespace WeatherApi.Controllers;

[ApiController]
[Route("auth")]
public class AuthController(JwtTokenBuilder _tokenBuilder, HttpClient _httpClient) : ControllerBase
{
    [HttpPost("login-by-code")]
    [AllowAnonymous]
    public async Task<IActionResult> LoginByCode([FromBody] LoginRequestBody body)
    {
        const string _baseUrl = "http://keycloak:8080";
        const string _clientId = "weather-api";
        const string _realm = "dev";
        string clientSecret = Environment.GetEnvironmentVariable("CLIENT_SECRET") ??
                throw new("Add the CLIENT_SECRET generated by your local keycloak server to the .env file at the project root!");
        var content = new FormUrlEncodedContent(new Dictionary<string, string>
        {
            { "grant_type", "authorization_code" },
            { "code", body.Code },
            { "client_id", _clientId },
            { "client_secret", clientSecret },
            { "redirect_uri", body.RedirectUri }
        });

        var response = await _httpClient.PostAsync($"{_baseUrl}/realms/{_realm}/protocol/openid-connect/token", content);
        response.EnsureSuccessStatusCode();
        var json = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(json);
        var accessToken = doc.RootElement.GetProperty("access_token").GetString();
        var username = GetUsernameClaim(accessToken);

        List<Claim> claims = [];
        if (!string.IsNullOrEmpty(username.Value))
        {
            claims.Add(new Claim(nameof(username), username.Value));
        }

        return Ok(new { accessToken = _tokenBuilder.Build(claims) });
    }

    public record LoginRequestBody(string Code, string RedirectUri);

    Claim GetUsernameClaim(string? token)
    {
        var handler = new JwtSecurityTokenHandler();
        var jwt = handler.ReadJwtToken(token);
        return jwt.Claims.FirstOrDefault(c => c.Type == "username" || c.Type == "preferred_username")
            ?? throw new Exception("Username claim not found");
    }
}
